Repository apache/cordova-lib, pull requests merged in 2019-11, with the labels that each got.

#817 Remove dead code in integration-tests/plugin.spec
  integration-tests/plugin.spec.js
Labels: enhancement

#816 Simplify jasmine configuration
  integration-tests/jasmine.json
  package.json
  spec/support/jasmine.json
Labels: enhancement

#818 Extend and improve plugin tests in preparation of supporting scoped plugins
  integration-tests/plugman_fetch.spec.js
  spec/cordova/platform/addHelper.spec.js
  spec/cordova/plugin/add.spec.js
  spec/cordova/util.spec.js
  spec/helpers.js
  spec/plugman/util/metadata.spec.js
Labels: enhancement

#822 refactor: eslint setup
  .eslintrc.yml
  integration-tests/.eslintrc.yml
  integration-tests/HooksRunner.spec.js
  integration-tests/fetch.spec.js
  integration-tests/pkgJson.spec.js
  integration-tests/platform.spec.js
  integration-tests/plugman_fetch.spec.js
  integration-tests/plugman_uninstall.spec.js
  package.json
  spec/.eslintrc.yml
  spec/cordova/build.spec.js
  spec/cordova/emulate.spec.js
  spec/cordova/platform/addHelper.spec.js
  spec/cordova/platform/remove.spec.js
  spec/cordova/plugin/add.getFetchVersion.spec.js
  spec/cordova/plugin/add.spec.js
  spec/cordova/plugin/index.spec.js
  spec/cordova/plugin/list.spec.js
  spec/cordova/plugin/remove.spec.js
  spec/cordova/prepare.spec.js
  spec/cordova/restore-util.spec.js
  spec/cordova/run.spec.js
  spec/cordova/serve.spec.js
  spec/cordova/util.spec.js
  spec/helpers.js
  spec/hooks/Context.spec.js
  spec/plugman/add_platform.spec.js
  spec/plugman/create.spec.js
  spec/plugman/install.spec.js
  spec/plugman/util/dependencies.spec.js
  spec/plugman/util/metadata.spec.js
  spec/project-test-helpers.js
  src/cordova/emulate.js
  src/cordova/plugin/add.js
  src/cordova/restore-util.js
  src/cordova/run.js
  src/cordova/serve.js
  src/cordova/targets.js
  src/plugman/create.js
  src/plugman/fetch.js
  src/plugman/install.js
  src/plugman/platform.js
  src/plugman/platform_operation.js
  src/plugman/uninstall.js
  src/plugman/util/default-engines.js
Labels: enhancement

#821 Support scoped plugins
  integration-tests/plugin.spec.js
  package.json
  spec/cordova/fixtures/plugins/@cordova/plugin-test-dummy/package.json
  spec/cordova/fixtures/plugins/@cordova/plugin-test-dummy/plugin.xml
  spec/cordova/platform/addHelper.spec.js
  spec/cordova/plugin/add.spec.js
  spec/cordova/plugin/plugin_spec_parser.spec.js
  spec/cordova/util.spec.js
  spec/plugman/util/metadata.spec.js
  src/cordova/platform/addHelper.js
  src/cordova/plugin/add.js
  src/cordova/plugin/plugin_spec_parser.js
  src/cordova/util.js
  src/plugman/install.js
  src/plugman/uninstall.js
  src/plugman/util/metadata.js
Labels: bug, enhancement

#823 test(e2e): re-enable HooksRunner#12 and move it to plugin#14
  integration-tests/HooksRunner.spec.js
  integration-tests/plugin.spec.js
Labels: enhancement

#826 test: use fs.copySync for increased performance
  spec/fixture-helper.js
Labels: enhancement

#827 fix: plugin installation from git url w/ semver
  integration-tests/pkgJson.spec.js
  src/plugman/fetch.js
Labels: bug

#803 Move tests from cordova/platform/{platform => addHelper}.spec
  spec/cordova/platform/addHelper.spec.js
  spec/cordova/platform/platform.spec.js
Labels: enhancement

#828 chore: consolidate eslint configs
  .eslintrc.yml
  integration-tests/.eslintrc.yml
  spec/.eslintrc.yml
Labels: enhancement
